// Code generated by "stringer -type Tag -trimprefix Tag ."; DO NOT EDIT.

package asn1ber

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TagEOC-0]
	_ = x[TagBoolean-1]
	_ = x[TagInteger-2]
	_ = x[TagBitString-3]
	_ = x[TagOctetString-4]
	_ = x[TagNULL-5]
	_ = x[TagObjectIdentifier-6]
	_ = x[TagObjectDescriptor-7]
	_ = x[TagExternal-8]
	_ = x[TagRealFloat-9]
	_ = x[TagEnumerated-10]
	_ = x[TagEmbeddedPDV-11]
	_ = x[TagUTF8String-12]
	_ = x[TagRelativeOID-13]
	_ = x[TagSequence-16]
	_ = x[TagSet-17]
	_ = x[TagNumericString-18]
	_ = x[TagPrintableString-19]
	_ = x[TagT61String-20]
	_ = x[TagVideotexString-21]
	_ = x[TagIA5String-22]
	_ = x[TagUTCTime-23]
	_ = x[TagGeneralizedTime-24]
	_ = x[TagGraphicString-25]
	_ = x[TagVisibleString-26]
	_ = x[TagGeneralString-27]
	_ = x[TagUniversalString-28]
	_ = x[TagCharacterString-29]
	_ = x[TagBMPString-30]
	_ = x[TagBitmask-31]
	_ = x[tagHigh-31]
	_ = x[tagHighContinueBitmask-128]
	_ = x[tagHighValueBitmask-127]
}

const (
	_Tag_name_0 = "EOCBooleanIntegerBitStringOctetStringNULLObjectIdentifierObjectDescriptorExternalRealFloatEnumeratedEmbeddedPDVUTF8StringRelativeOID"
	_Tag_name_1 = "SequenceSetNumericStringPrintableStringT61StringVideotexStringIA5StringUTCTimeGeneralizedTimeGraphicStringVisibleStringGeneralStringUniversalStringCharacterStringBMPStringBitmask"
	_Tag_name_2 = "tagHighValueBitmasktagHighContinueBitmask"
)

var (
	_Tag_index_0 = [...]uint8{0, 3, 10, 17, 26, 37, 41, 57, 73, 81, 90, 100, 111, 121, 132}
	_Tag_index_1 = [...]uint8{0, 8, 11, 24, 39, 48, 62, 71, 78, 93, 106, 119, 132, 147, 162, 171, 178}
	_Tag_index_2 = [...]uint8{0, 19, 41}
)

func (i Tag) String() string {
	switch {
	case i <= 13:
		return _Tag_name_0[_Tag_index_0[i]:_Tag_index_0[i+1]]
	case 16 <= i && i <= 31:
		i -= 16
		return _Tag_name_1[_Tag_index_1[i]:_Tag_index_1[i+1]]
	case 127 <= i && i <= 128:
		i -= 127
		return _Tag_name_2[_Tag_index_2[i]:_Tag_index_2[i+1]]
	default:
		return "Tag(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
