// Code generated by "stringer -type Type -trimprefix Type ."; DO NOT EDIT.

package ber

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypePrimitive-0]
	_ = x[TypeConstructed-32]
}

const (
	_Type_name_0 = "Primitive"
	_Type_name_1 = "Constructed"
)

func (i Type) String() string {
	switch {
	case i == 0:
		return _Type_name_0
	case i == 32:
		return _Type_name_1
	default:
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
