// Code generated by "stringer -type Scope -trimprefix Scope"; DO NOT EDIT.

package ldap

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ScopeBaseObject-0]
	_ = x[ScopeSingleLevel-1]
	_ = x[ScopeWholeSubtree-2]
}

const _Scope_name = "BaseObjectSingleLevelWholeSubtree"

var _Scope_index = [...]uint8{0, 10, 21, 33}

func (i Scope) String() string {
	if i < 0 || i >= Scope(len(_Scope_index)-1) {
		return "Scope(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Scope_name[_Scope_index[i]:_Scope_index[i+1]]
}
